# Update below configuration
global:
        smtp_smarthost: 'smtps_server_name:25' # Update SMTP server details
  smtp_from: 'sender@example.com' # Update email from information
  smtp_require_tls: false

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 2m
  group_interval: 2m
  repeat_interval: 24h
  receiver: 'receiver-mails'
receivers:
- name: 'receiver-mails'
  email_configs:
  - to: 'receiver@example.com'  #Update all receivers email id
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
